"""
Django settings for emailver project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-zr*n+*b1v%xb2squ$mi%t)pjxkuxgr7j+)#io5pac7=0a)8$--'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = [
    '*',
    'chiwegames.com',
    'chiwe.onrender.com',
    'exaon.tech',
    '127.0.0.1',
    'localhost',
    '8193a66d4544.ngrok-free.app',
]

DATABASE_URL="postgresql://chiwedb_user:W2vQaHBpqZojxG9a5M5N7nHQamFbXIoM@dpg-d31a6l15pdvs73901vgg-a.oregon-postgres.render.com/chiwedb"
# Application definition
CORS_ALLOW_CREDENTIALS = True

INSTALLED_APPS = [
    'autapp',
    'channels',
    'daphne',
    'Games',
    'monitary',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps'
    
]
# let the page be embedded (needed for Pi Sandbox)
X_FRAME_OPTIONS = "ALLOWALL"  # disables the DENY header

APPEND_SLASH=True
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}
CSRF_TRUSTED_ORIGINS = [
    'https://8193a66d4544.ngrok-free.app',
    'https://chiwe.onrender.com',
    'https://exaon.tech',
    'https://chiwegames.com',
    'https://sandbox.minepi.com',
]

MIDDLEWARE = [
    
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

ROOT_URLCONF = 'emailver.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'emailver.wsgi.application'
ASGI_APPLICATION = 'emailver.asgi.application'

# Cookie and CSRF security settings
# For development (DEBUG=True) allow cookies over HTTP so browsers
# running on localhost can accept session cookies. In production
# enforce secure cookies and SameSite=None for cross-site flows.
# Cookie and CSRF security settings
# For development with ngrok and cross-origin flows (Pi sandbox) we need
# cookies to be sent in cross-site requests. Set SameSite=None and Secure=True
# when using HTTPS (ngrok provides HTTPS). If you run locally over plain HTTP
# without ngrok, consider toggling these appropriately.
if DEBUG:
    # When developing via ngrok (HTTPS) set cookies to be cross-site and secure
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SAMESITE = 'None'
    CSRF_COOKIE_SAMESITE = 'None'
    SESSION_COOKIE_DOMAIN = None
else:
    CSRF_COOKIE_SAMESITE = "None"
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SAMESITE = "None"
    SESSION_COOKIE_SECURE = True
    # If you want the session cookie to be valid for specific domains, set here
    SESSION_COOKIE_DOMAIN = ".ngrok-free.app"

# Ensure Django trusts the forwarded proto header (ngrok sets it)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=DATABASE_URL,
        conn_max_age=600,        # persist connections
        ssl_require=True         # enforce SSL
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'rate-limit-cache',      # just a unique name
        'TIMEOUT': None,                     # or a default timeout in seconds
        'OPTIONS': {
            'MAX_ENTRIES': 10000,            # how many keys before it starts evicting
        }
    }
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_REDIRECT_URL='/dashboard'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = "smtp.gmail.com"
EMAIL_HOST_USER = "chiweVerify@gmail.com"
EMAIL_HOST_PASSWORD = "vwcpzdzshcxilrwm"
EMAIL_PORT = 587
EMAIL_TIMEOUT = 30
AUTH_USER_MODEL = 'autapp.MyUser'
# Note: final cookie security values are set above depending on DEBUG.
SECURE_SSL_REDIRECT = False
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    # Add other authentication backends if you have any
]

