# Generated by Django 5.1.4 on 2025-06-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autapp', '0008_chiweprofit_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='firstdepo',
            field=models.BooleanField(default=False),
        ),
    ]
