# Generated by Django 5.0.7 on 2025-07-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autapp', '0009_myuser_firstdepo'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='refered',
            field=models.CharField(blank=True, default=False),
        ),
    ]
