# Generated by Django 5.0.7 on 2025-07-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autapp', '0010_myuser_refered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='refered',
            new_name='referedBy',
        ),
        migrations.AddField(
            model_name='ballance',
            name='deposited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='referalCode',
            field=models.IntegerField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='referedCount',
            field=models.IntegerField(default=0),
        ),
    ]
