# Generated by Django 5.0.7 on 2025-07-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autapp', '0011_rename_refered_myuser_referedby_ballance_deposited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='referalCode',
            field=models.CharField(blank=True, default=False),
        ),
    ]
