# Generated by Django 5.0.7 on 2025-09-17 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autapp', '0012_alter_myuser_referalcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='PiPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('memo', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='created', max_length=32)),
                ('txid', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
