# Generated by Django 5.1.4 on 2025-06-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='way',
            field=models.CharField(default='tb', max_length=20),
        ),
    ]
