# Generated by Django 5.1.4 on 2025-06-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitary', '0002_withdrawalrequest_way'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ebirreq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_id', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
