# Generated by Django 5.1.4 on 2025-06-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitary', '0003_ebirreq'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebirreq',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
