# Generated by Django 5.1.4 on 2025-06-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitary', '0004_ebirreq_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebirreq',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
