# Generated by Django 5.1.4 on 2025-06-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitary', '0005_alter_ebirreq_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='firstdepo',
            field=models.BooleanField(default=False),
        ),
    ]
