# Generated by Django 5.1.4 on 2025-06-08 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitary', '0006_withdrawalrequest_firstdepo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='firstdepo',
        ),
    ]
