# Generated by Django 5.0.7 on 2025-07-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitary', '0007_remove_withdrawalrequest_firstdepo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField()),
                ('amount', models.DecimalField(decimal_places=10, max_digits=10)),
                ('cryptoType', models.CharField()),
                ('orderid', models.IntegerField(default=0)),
                ('status', models.CharField(default='pending')),
            ],
        ),
    ]
