# Generated by Django 5.0.7 on 2025-07-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitary', '0008_cryptopayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cryptopayment',
            old_name='cryptoType',
            new_name='currency',
        ),
        migrations.RemoveField(
            model_name='cryptopayment',
            name='orderid',
        ),
        migrations.AddField(
            model_name='cryptopayment',
            name='order_id',
            field=models.CharField(default=0),
        ),
    ]
