# Generated by Django 5.0.7 on 2025-07-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitary', '0009_rename_cryptotype_cryptopayment_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptopayment',
            name='order_id',
            field=models.CharField(max_length=100),
        ),
    ]
