# Generated by Django 5.0.7 on 2025-07-12 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitary', '0010_alter_cryptopayment_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptopayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
