# Generated by Django 5.0.7 on 2025-08-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitary', '0011_alter_cryptopayment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='phone_number',
            field=models.CharField(max_length=100),
        ),
    ]
